### ISSUE TITLE
Create Sponsorship Package Doc - May 30

### ISSUE THREAD

**Issue by lequanne** [intersectto/BIPOC-Hackathon#6]
You got this!

**Comment by char-siuu-bao** [comment]
Working on sponsorship doc here:  https://docs.google.com/document/d/1izcvD54-1pEm2S1rSo61QJy0hQ_egvGpevjwbVvdnZs/edit 

It's in progress - @byvivian feel free to edit/comment/suggest!

**Comment by byvivian** [comment]
@lorrainechu3n added in a bit, but otherwise looks good -- just let me know when you've worked on it again or if you want me to work specifically on something :)

**Comment by aljumaine** [comment]
@lorrainechu3n @byvivian and Team: I had a look at the document and it's great. I don't find the requirements of the sponsors to be too strict. It would also make it clear that we are only interested in long-term relationships for supporting our community. 

@lorrainechu3n - I was also wondering about how we will hold the funds we receive from sponsors. Would it be best if Intersect TO was to register as an NGO and then acquire an NGO bank account? 

We would also be able to issue tax receipts to the sponsors so that they will strongly consider long-term support of our community and events/programming.  Would it also make sense for there to be a sponsorship/ partnership page on the website to display our supporters? 

What do you all think? 

**Guidelines:** 
https://docs.google.com/document/d/1izcvD54-1pEm2S1rSo61QJy0hQ_egvGpevjwbVvdnZs/edit#heading=h.l2t35xyi7d3u

**Comment by char-siuu-bao** [comment]
Yep great question @aljumaine ! This is something I mentioned on Slack and really wanted to bring up on our last call.  It costs some money to register as a nonprofit (and doing some research online, we also need a board of directors, and they maybe recommend you finding a lawyer to help navigate the process??) - so I think it would be tricky to do within a month.

The other option is finding a fiscal sponsor - so a nonprofit that can help us process and hold funds. That's something I think Lequanne and I wanted to consider, but we should talk through as a group! Typically, the fiscal sponsor takes some percentage (small-ish, like 10%) of whatever funds you raise / grants you receive in exchange for helping administer funds. Because the in-kind sponsor has nonprofit/charity status, I think that means operating under them, we'd still be able to issue tax receipts. (But I need to double check this!) - I think this is the best option for us to look into long term; we just need to find and secure a fiscal sponsor!!  More info here --> https://www.councilofnonprofits.org/tools-resources/fiscal-sponsorship-nonprofits

The other option, which I think _might_ be most straightforward for this event (since it's coming up so soon) is just to ask for in-kind sponsorships. So rather than organizations giving us *money* (and then we pay for catering etc...), we could ask them to sponsor the food / swag directly (which is why I've labelled the sponsorship as **"in kind"** sponsorship options in the doc) -->  i.e. we invoice our catering order to them, etc... that way funds never pass our hands. That's how Wattpad supported our dinner during the last co-design session, they paid for the pizza directly :)  I think that might actually be simplest given our timeline, but I could also be wrong, and I would love love love to chat through the other options + do some collective research on this! 

It's definitely an important convo to have in the long term too, and I'd love to secure a fiscal sponsor (or look into registering as a NP) sooner rather than later.   Thanks for bringing it up Al!

**Comment by char-siuu-bao** [comment]
Some more info on incorporating an NFP here: https://www.ontario.ca/page/incorporating-not-profit-corporation 

and 

https://www.attorneygeneral.jus.gov.on.ca/english/family/pgt/nfpinc/Not_for_Profit_Incorporators_Handbook_EN.html

**Comment by char-siuu-bao** [comment]
A Q was also posted in the civicTechTO slack a few months ago on how to register an NPO and here's what one of the members shared as the process:

"The process is more or less like this:
1) Find lawyer, have them do an internal conflict of interest check on representing you
2) Fill out some forms and make some decisions about how you're going to be structured & what you want to pay them for
3) Get a name check done (to make sure nobody else has registered the business name you want)
4) Get the paperwork filed with Industry Canada (or whatever they're called right now), and wait for approval."

they also wrote that it should cost around 600$ (including legal fees) and take about a month minimum to walk through all the steps ....

**Comment by byvivian** [comment]
For now, at least this event, it seems like the in-kind option is the best way to go. And maybe even continue on this path a bit until we have more time to figure out which avenue to take? Given the short timeline let's just make it as easy as possible and then research further for down the road.

**Comment by aljumaine** [comment]
Hey team,

I totally agree with Vivian with in-kind- option. I have a few pals that
are LLB's that may be able to swing this pro bono.
I'll most likely need until early next week to sort that out.

Bst,

Aljumaine Gayle
M: 647-834-3384
aljumaine.com

I respectfully acknowledge that I live and work on the traditional
territory of the Huron-Wendat and Petun First Nations, the Seneca, and most
recently, the Mississaugas of the New Credit. I am grateful to have the
opportunity to live in the community, on this territory.

**Comment by aljumaine** [comment]
Thank you, Lorraine, for outlining the process for registering as an NGO. :)

Aljumaine Gayle
M: 647-834-3384
aljumaine.com

I respectfully acknowledge that I live and work on the traditional
territory of the Huron-Wendat and Petun First Nations, the Seneca, and most
recently, the Mississaugas of the New Credit. I am grateful to have the
opportunity to live in the community, on this territory.

**Comment by byvivian** [comment]
this is done
